language: scala
scala:
   - 2.12.1
jdk:
  - oraclejdk8
before_script:
  # pull down gwen source dependency
  - cd ..
  - git clone https://github.com/gwen-interpreter/gwen.git
  - cd gwen-web
  # use virtual frame buffers to run browser tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/