language: scala
scala:
   - 2.10.6
   - 2.11.7
jdk:
  - oraclejdk8
  - oraclejdk7
before_script:
  - cd ..
  - git clone https://github.com/gwen-interpreter/gwen.git
  - cd gwen-web
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start